flyway.url=jdbc:cassandra://localhost:9042/chatapp
flyway.user=cassandra
flyway.password=cassandra
flyway.schemas=chatapp
flyway.locations=filesystem:./flyway/sql
flyway.driver=./flyway/drivers/cassandra-jdbc-wrapper.jar